### ISSUE TITLE
Bug: When parsing issuance of assets (and probably more)

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/worker#1]
#### How to replicate:

1. Install and Setup both Multichain & Explorer
2. Run the explorer with ``python -m Mce.abe --config chain1.conf &``
3. Issue an asset to someone through ``multichain-cli chain1 issue 1XXXXXXWTkXXXXXXGMXXXXXXSFXXXXXXckeFSF "Dollar" 100``.
4. Watch parser brakes

#### Console Output:
```
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 1, 'loader': u'default', 'conf': None, 'dirname': u'/home/tloriato/.multichain/chain1', 'id': 8L}
Traceback (most recent call last):
  File "Mce/DataStore.py", line 2899, in catch_up
    if not store.catch_up_rpc(dircfg):
  File "Mce/DataStore.py", line 3132, in catch_up_rpc
    store.import_block(block, chain = chain)
  File "Mce/DataStore.py", line 1199, in import_block
    tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)
  File "Mce/DataStore.py", line 2221, in import_and_commit_tx
    tx_id = store.import_tx(tx, is_coinbase, chain)
  File "Mce/DataStore.py", line 2012, in import_tx
    store.update_asset_address_balance(new_asset_id, pubkey_id, val, tx['hash']);
  File "Mce/DataStore.py", line 2209, in update_asset_address_balance
    (asset_id, pubkey_id))
  File "Mce/DataStore.py", line 262, in sql
    store._sql.sql(stmt, params)
  File "Mce/SqlAbstraction.py", line 489, in sql
    sql._execute(cached, params)
  File "Mce/SqlAbstraction.py", line 470, in _execute
    sql.cursor().execute(stmt, params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR IGNORE INTO asset_address_balance (asset_id, pubkey_id, balance)\n            ' at line 1")
```
#### Interpretation:

One of the SQL queries (or multiple ones) aren't valid for MySQLDB. It should be reasonable simple to fix them, the catch is to track them.

#### Suggestions:

I wrote some print commands in the last commit to show the queries right before it broke down, on line `` ~ 470`` of ``Mce/DataStore.py``

**Comment by tloriato** [comment]
```
=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326ae50d0>

== STMT ==


                SELECT configvar_name, configvar_value
                  FROM configvar

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT datadir_id, dirname, blkfile_number, blkfile_offset,
                   chain_id
              FROM datadir

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

SELECT chain_id FROM chain WHERE chain_name = %s

== PARAMS ==

(u'MultiChain chain1',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

INSERT INTO datadir_seq () VALUES ()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

SELECT LAST_INSERT_ID()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                    SELECT chain_id, chain_magic, chain_name, chain_code3,
                           chain_address_checksum, chain_address_version, chain__addr_vers, chain_policy, chain_decimals,
                           chain_protocol_version
                      FROM chain
                

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT block_height
              FROM chain_candidate
             WHERE chain_id = %s
               AND in_longest = 1
             ORDER BY block_height DESC
             LIMIT 1

== PARAMS ==

(1,)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                    SELECT 1
                      FROM chain_candidate cc
                      JOIN block b ON (cc.block_id = b.block_id)
                     WHERE b.block_hash = %s
                       AND b.block_height IS NOT NULL
                       AND cc.chain_id = %s

== PARAMS ==

('\x00RV\xb2h\xc1\xf9\x9a\x10\xa3:\xaf\xf9\xe3\x9e\x12c\x9bJ\xa8\x9bpI\xa0\x94\xabb\xb7_\r\x9f\xc8', 1)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT block_id, block_height, block_chain_work,
                   block_nTime, block_total_seconds,
                   block_total_satoshis, block_satoshi_seconds,
                   block_total_ss
              FROM block
             WHERE block_hash = %s
        

== PARAMS ==

('\x00\x88w\x94\x93:o\xb3\xe4"\xa5j\x0f\xad\xeb\xcc.E\xda\xa3\xccx\xd9\xe5f\xc8\xedH%G\xc0\x9d',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                SELECT tx_id, tx_version, tx_lockTime, tx_size
                  FROM tx
                 WHERE tx_hash = %s
            

== PARAMS ==

('w\xd9\x14\x91\xbf\x9b,y\x9f\xcf\x84\xb5\xaa~\xc7\x8c\xd1P X8.\x88o\x95\x82\xdfc\xab\xc5\xc1{',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT
                COALESCE(tx.tx_hash, uti.txout_tx_hash),
                COALESCE(txout.txout_pos, uti.txout_pos),
                txin_Sig,
                txin_sequence
            FROM txin
            LEFT JOIN txout ON (txin.txout_id = txout.txout_id)
            LEFT JOIN tx ON (txout.tx_id = tx.tx_id)
            LEFT JOIN unlinked_txin uti ON (txin.txin_id = uti.txin_id)
            WHERE txin.tx_id = %s
            ORDER BY txin.txin_pos

== PARAMS ==

(Decimal('64'),)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT txout_value, txout_PubKey
              FROM txout
             WHERE tx_id = %s
            ORDER BY txout_pos

== PARAMS ==

(Decimal('64'),)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                SELECT tx_id, tx_version, tx_lockTime, tx_size
                  FROM tx
                 WHERE tx_hash = %s
            

== PARAMS ==

('e\xd4\xc9\xc0^m\xe7\x12\xeb\xc9t\xf4\xf5\xf0\x89\xdb\xe6H\xde\x8c\x03\xc3E\xc0\xb8&:y\x10K0(',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT tx.tx_id, SUM(txout.txout_value), SUM(
                       CASE WHEN txout.pubkey_id > 0 THEN txout.txout_value
                            ELSE 0 END)
              FROM tx
              LEFT JOIN txout ON (tx.tx_id = txout.tx_id)
             WHERE tx_hash = %s
             GROUP BY tx.tx_id

== PARAMS ==

('w\xd9\x14\x91\xbf\x9b,y\x9f\xcf\x84\xb5\xaa~\xc7\x8c\xd1P X8.\x88o\x95\x82\xdfc\xab\xc5\xc1{',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                SELECT COUNT(1), SUM(prevout.txout_value)
                  FROM txin
                  JOIN txout prevout ON (txin.txout_id = prevout.txout_id)
                 WHERE txin.tx_id = %s

== PARAMS ==

(Decimal('64'),)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT tx.tx_id, SUM(txout.txout_value), SUM(
                       CASE WHEN txout.pubkey_id > 0 THEN txout.txout_value
                            ELSE 0 END)
              FROM tx
              LEFT JOIN txout ON (tx.tx_id = txout.tx_id)
             WHERE tx_hash = %s
             GROUP BY tx.tx_id

== PARAMS ==

('e\xd4\xc9\xc0^m\xe7\x12\xeb\xc9t\xf4\xf5\xf0\x89\xdb\xe6H\xde\x8c\x03\xc3E\xc0\xb8&:y\x10K0(',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

INSERT INTO tx_seq () VALUES ()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

SELECT LAST_INSERT_ID()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            INSERT INTO tx (tx_id, tx_hash, tx_version, tx_lockTime, tx_size)
            VALUES (%s, %s, %s, %s, %s)

== PARAMS ==

(67L, 'e\xd4\xc9\xc0^m\xe7\x12\xeb\xc9t\xf4\xf5\xf0\x89\xdb\xe6H\xde\x8c\x03\xc3E\xc0\xb8&:y\x10K0(', 1, 0, 271)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

INSERT INTO txout_seq () VALUES ()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

SELECT LAST_INSERT_ID()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT pubkey_id
              FROM pubkey
             WHERE pubkey_hash = %s

== PARAMS ==

('\xe1\xdc\xa8e\x10L\x1b\x93\x08#\x8b? \xad.\x91t\xc8\x86H',)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                INSERT INTO txout (
                    txout_id, tx_id, txout_pos, txout_value,
                    txout_PubKey, pubkey_id
                ) VALUES (%s, %s, %s, %s, %s, %s)

== PARAMS ==

(70L, 67L, 0, 0, 'v\xa9\x14\xe1\xdc\xa8e\x10L\x1b\x93\x08#\x8b? \xad.\x91t\xc8\x86H\x88\xac\x0cspkgd\x00\x00\x00\x00\x00\x00\x00u', Decimal('2'))

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                SELECT unlinked_txin.txin_id, tx_hash, txin_pos
                  FROM unlinked_txin LEFT JOIN txin ON (unlinked_txin.txin_id = txin.txin_id) LEFT JOIN tx ON (txin.tx_id = tx.tx_id)
                 WHERE txout_tx_hash = %s
                   AND txout_pos = %s

== PARAMS ==

('e\xd4\xc9\xc0^m\xe7\x12\xeb\xc9t\xf4\xf5\xf0\x89\xdb\xe6H\xde\x8c\x03\xc3E\xc0\xb8&:y\x10K0(', 0)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                             SELECT asset_id FROM asset WHERE asset.prefix = %s
                             

== PARAMS ==

(54373,)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

INSERT INTO asset_seq () VALUES ()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==

SELECT LAST_INSERT_ID()

== PARAMS ==

()

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


                                INSERT INTO asset (asset_id, tx_id, chain_id, name, multiplier, issue_qty, prefix)
                                VALUES (%s, %s, %s, %s, %s, %s, %s)

== PARAMS ==

(3L, 67L, 1, '', 0, 100, 54373)

=== Linha 476 ===


=== Teste Fim ===


=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            INSERT OR IGNORE INTO asset_address_balance (asset_id, pubkey_id, balance)
            VALUES (%s,%s,0)

== PARAMS ==

(3L, Decimal('2'))

=== Teste Inicio ===


== SQL ==

<Mce.SqlAbstraction.SqlAbstraction object at 0x7f1326afcf50>

== STMT ==


            SELECT tx.tx_id, SUM(txout.txout_value), SUM(
                       CASE WHEN txout.pubkey_id > 0 THEN txout.txout_value
                            ELSE 0 END)
              FROM tx
              LEFT JOIN txout ON (tx.tx_id = txout.tx_id)
             WHERE tx_hash = %s
             GROUP BY tx.tx_id

== PARAMS ==

('e\xd4\xc9\xc0^m\xe7\x12\xeb\xc9t\xf4\xf5\xf0\x89\xdb\xe6H\xde\x8c\x03\xc3E\xc0\xb8&:y\x10K0(',)

=== Linha 476 ===


=== Teste Fim ===

Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 1, 'loader': u'default', 'conf': None, 'dirname': u'/home/tloriato/.multichain/chain1', 'id': 7L}
Traceback (most recent call last):
  File "Mce/DataStore.py", line 2899, in catch_up
    if not store.catch_up_rpc(dircfg):
  File "Mce/DataStore.py", line 3132, in catch_up_rpc
    store.import_block(block, chain = chain)
  File "Mce/DataStore.py", line 1199, in import_block
    tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)s
  File "Mce/DataStore.py", line 2221, in import_and_commit_tx
    tx_id = store.import_tx(tx, is_coinbase, chain)
  File "Mce/DataStore.py", line 2012, in import_tx
    store.update_asset_address_balance(new_asset_id, pubkey_id, val, tx['hash']);
  File "Mce/DataStore.py", line 2209, in update_asset_address_balance
    (asset_id, pubkey_id))
  File "Mce/DataStore.py", line 262, in sql
    store._sql.sql(stmt, params)
  File "Mce/SqlAbstraction.py", line 496, in sql
    sql._execute(cached, params)
  File "Mce/SqlAbstraction.py", line 475, in _execute
    sql.cursor().execute(stmt, params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR IGNORE INTO asset_address_balance (asset_id, pubkey_id, balance)\n            ' at line 1")


```
